// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { FetchData, FetchError, FetchResponse, StateData, StateError, StateResponse, LogfilePathData, LogfilePathError, LogfilePathResponse, PushLogsData, PushLogsError, PushLogsResponse, RegisterData, RegisterError, RegisterResponse, SetStateData, SetStateError, SetStateResponse, UpdateQueuesData, UpdateQueuesError, UpdateQueuesResponse, HealthError, HealthResponse, WorkerData, WorkerError, WorkerResponse, JobsData, JobsError, JobsResponse, RequestWorkerMaintenanceData, RequestWorkerMaintenanceError, RequestWorkerMaintenanceResponse, UpdateWorkerMaintenanceData, UpdateWorkerMaintenanceError, UpdateWorkerMaintenanceResponse, ExitWorkerMaintenanceData, ExitWorkerMaintenanceError, ExitWorkerMaintenanceResponse, RequestWorkerShutdownData, RequestWorkerShutdownError, RequestWorkerShutdownResponse, DeleteWorkerData, DeleteWorkerError, DeleteWorkerResponse, AddWorkerQueueData, AddWorkerQueueError, AddWorkerQueueResponse, RemoveWorkerQueueData, RemoveWorkerQueueError, RemoveWorkerQueueResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Fetch
 * Fetch a job to execute on the edge worker.
 */
export const fetch = <ThrowOnError extends boolean = false>(options: Options<FetchData, ThrowOnError>) => { return (options?.client ?? client).post<FetchResponse, FetchError, ThrowOnError>({
    ...options,
    url: '/edge_worker/v1/jobs/fetch/{worker_name}'
}); };

/**
 * State
 * Update the state of a job running on the edge worker.
 */
export const state = <ThrowOnError extends boolean = false>(options: Options<StateData, ThrowOnError>) => { return (options?.client ?? client).patch<StateResponse, StateError, ThrowOnError>({
    ...options,
    url: '/edge_worker/v1/jobs/state/{dag_id}/{task_id}/{run_id}/{try_number}/{map_index}/{state}'
}); };

/**
 * Logfile Path
 * Elaborate the path and filename to expect from task execution.
 */
export const logfilePath = <ThrowOnError extends boolean = false>(options: Options<LogfilePathData, ThrowOnError>) => { return (options?.client ?? client).get<LogfilePathResponse, LogfilePathError, ThrowOnError>({
    ...options,
    url: '/edge_worker/v1/logs/logfile_path/{dag_id}/{task_id}/{run_id}/{try_number}/{map_index}'
}); };

/**
 * Push Logs
 * Push an incremental log chunk from Edge Worker to central site.
 */
export const pushLogs = <ThrowOnError extends boolean = false>(options: Options<PushLogsData, ThrowOnError>) => { return (options?.client ?? client).post<PushLogsResponse, PushLogsError, ThrowOnError>({
    ...options,
    url: '/edge_worker/v1/logs/push/{dag_id}/{task_id}/{run_id}/{try_number}/{map_index}'
}); };

/**
 * Register
 * Register a new worker to the backend.
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => { return (options?.client ?? client).post<RegisterResponse, RegisterError, ThrowOnError>({
    ...options,
    url: '/edge_worker/v1/worker/{worker_name}'
}); };

/**
 * Set State
 * Set state of worker and returns the current assigned queues.
 */
export const setState = <ThrowOnError extends boolean = false>(options: Options<SetStateData, ThrowOnError>) => { return (options?.client ?? client).patch<SetStateResponse, SetStateError, ThrowOnError>({
    ...options,
    url: '/edge_worker/v1/worker/{worker_name}'
}); };

/**
 * Update Queues
 */
export const updateQueues = <ThrowOnError extends boolean = false>(options: Options<UpdateQueuesData, ThrowOnError>) => { return (options?.client ?? client).patch<UpdateQueuesResponse, UpdateQueuesError, ThrowOnError>({
    ...options,
    url: '/edge_worker/v1/worker/queues/{worker_name}'
}); };

/**
 * Health
 * Report API Health.
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<HealthResponse, HealthError, ThrowOnError>({
    ...options,
    url: '/edge_worker/v1/health'
}); };

/**
 * Worker
 * Return Edge Workers.
 */
export const worker = <ThrowOnError extends boolean = false>(options?: Options<WorkerData, ThrowOnError>) => { return (options?.client ?? client).get<WorkerResponse, WorkerError, ThrowOnError>({
    ...options,
    url: '/edge_worker/ui/worker'
}); };

/**
 * Jobs
 * Return Edge Jobs.
 */
export const jobs = <ThrowOnError extends boolean = false>(options?: Options<JobsData, ThrowOnError>) => { return (options?.client ?? client).get<JobsResponse, JobsError, ThrowOnError>({
    ...options,
    url: '/edge_worker/ui/jobs'
}); };

/**
 * Request Worker Maintenance
 * Put a worker into maintenance mode.
 */
export const requestWorkerMaintenance = <ThrowOnError extends boolean = false>(options: Options<RequestWorkerMaintenanceData, ThrowOnError>) => { return (options?.client ?? client).post<RequestWorkerMaintenanceResponse, RequestWorkerMaintenanceError, ThrowOnError>({
    ...options,
    url: '/edge_worker/ui/worker/{worker_name}/maintenance'
}); };

/**
 * Update Worker Maintenance
 * Update maintenance comments for a worker.
 */
export const updateWorkerMaintenance = <ThrowOnError extends boolean = false>(options: Options<UpdateWorkerMaintenanceData, ThrowOnError>) => { return (options?.client ?? client).patch<UpdateWorkerMaintenanceResponse, UpdateWorkerMaintenanceError, ThrowOnError>({
    ...options,
    url: '/edge_worker/ui/worker/{worker_name}/maintenance'
}); };

/**
 * Exit Worker Maintenance
 * Exit a worker from maintenance mode.
 */
export const exitWorkerMaintenance = <ThrowOnError extends boolean = false>(options: Options<ExitWorkerMaintenanceData, ThrowOnError>) => { return (options?.client ?? client).delete<ExitWorkerMaintenanceResponse, ExitWorkerMaintenanceError, ThrowOnError>({
    ...options,
    url: '/edge_worker/ui/worker/{worker_name}/maintenance'
}); };

/**
 * Request Worker Shutdown
 * Request shutdown of a worker.
 */
export const requestWorkerShutdown = <ThrowOnError extends boolean = false>(options: Options<RequestWorkerShutdownData, ThrowOnError>) => { return (options?.client ?? client).post<RequestWorkerShutdownResponse, RequestWorkerShutdownError, ThrowOnError>({
    ...options,
    url: '/edge_worker/ui/worker/{worker_name}/shutdown'
}); };

/**
 * Delete Worker
 * Delete a worker record from the system.
 */
export const deleteWorker = <ThrowOnError extends boolean = false>(options: Options<DeleteWorkerData, ThrowOnError>) => { return (options?.client ?? client).delete<DeleteWorkerResponse, DeleteWorkerError, ThrowOnError>({
    ...options,
    url: '/edge_worker/ui/worker/{worker_name}'
}); };

/**
 * Add Worker Queue
 * Add a queue to a worker.
 */
export const addWorkerQueue = <ThrowOnError extends boolean = false>(options: Options<AddWorkerQueueData, ThrowOnError>) => { return (options?.client ?? client).put<AddWorkerQueueResponse, AddWorkerQueueError, ThrowOnError>({
    ...options,
    url: '/edge_worker/ui/worker/{worker_name}/queues/{queue_name}'
}); };

/**
 * Remove Worker Queue
 * Remove a queue from a worker.
 */
export const removeWorkerQueue = <ThrowOnError extends boolean = false>(options: Options<RemoveWorkerQueueData, ThrowOnError>) => { return (options?.client ?? client).delete<RemoveWorkerQueueResponse, RemoveWorkerQueueError, ThrowOnError>({
    ...options,
    url: '/edge_worker/ui/worker/{worker_name}/queues/{queue_name}'
}); };